name: Build Zed on Windows

on:
  push:
    branches: [main]       # or your default branch

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up CMake
        # windows-latest already has CMake, but you can ensure the right version:
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.26.4'  # pick whatever you need

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Build (release)
        shell: powershell
        run: |
          cargo clean
          cargo run --release

      # Optionally, upload the built binary as an artifact:
      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: zed-windows-release
          path: target\release\zed.exe
