# .github/workflows/ci.yml
name: Compile Zed on Linux for Windows

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-windows-on-linux:
    name: Build Windows.exe + MSI (on Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 msitools

      - name: Install Rust toolchain & Windows target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: rustup target add x86_64-pc-windows-gnu

      - name: Build Windows .exe
        run: |
          cargo build --release --target x86_64-pc-windows-gnu

      - name: Prepare WiX source for MSI
        run: |
          mkdir -p installer
          cat > installer/zed.wxs << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
            <Product Id="*" Name="zed" Language="1033" Version="1.0.0.0"
                     Manufacturer="zed-industries" UpgradeCode="PUT-GUID-HERE">
              <Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" />

              <!-- Define the directory structure -->
              <Directory Id="TARGETDIR" Name="SourceDir">
                <Directory Id="ProgramFilesFolder">
                  <Directory Id="INSTALLFOLDER" Name="zed" />
                </Directory>
                <Directory Id="ProgramMenuFolder">
                  <Directory Id="ZedStartMenuDir" Name="zed" />
                </Directory>
              </Directory>

              <!-- Component: the EXE -->
              <DirectoryRef Id="INSTALLFOLDER">
                <Component Id="cmpZedExe" Guid="ANOTHER-GUID">
                  <File Id="zedExe"
                        Source="target/x86_64-pc-windows-gnu/release/zed.exe"
                        KeyPath="yes" />
                </Component>
              </DirectoryRef>

              <!-- Shortcut in Start Menu -->
              <DirectoryRef Id="ZedStartMenuDir">
                <Component Id="cmpStartMenuShort" Guid="YET-ANOTHER-GUID">
                  <Shortcut Id="ZedStartMenuLink"
                            Name="zed"
                            Target="[INSTALLFOLDER]zed.exe"
                            WorkingDirectory="INSTALLFOLDER"/>
                  <RemoveFolder Id="RemoveZedStartMenuDir"
                                Directory="ZedStartMenuDir"
                                On="uninstall"/>
                  <RegistryValue Root="HKCU"
                                 Key="Software/zed"
                                 Name="installed"
                                 Type="integer"
                                 Value="1"
                                 KeyPath="yes"/>
                </Component>
              </DirectoryRef>

              <Feature Id="MainFeature" Title="zed" Level="1">
                <ComponentRef Id="cmpZedExe"/>
                <ComponentRef Id="cmpStartMenuShort"/>
              </Feature>
            </Product>
          </Wix>
          EOF

      - name: Compile WiX → MSI
        run: |
          candle installer/zed.wxs -o installer/zed.wixobj
          light installer/zed.wixobj -o zed.msi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: |
            target/x86_64-pc-windows-gnu/release/zed.exe
            zed.msi
