name: Windows build & MSI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust, target & dependencies
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          rustup default stable
          rustup target add x86_64-pc-windows-gnu
          sudo apt-get update
          sudo apt-get install -y mingw-w64 cmake wine64 wine32 unzip

      - name: Build `zed.exe`
        run: |
          source $HOME/.cargo/env
          cargo build --release --target x86_64-pc-windows-gnu

      - name: Install WiX Toolset under Wine
        run: |
          curl -L -o wix.zip https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix311-binaries.zip
          unzip wix.zip -d wix
          export PATH=$PWD/wix/bin:$PATH

      - name: Generate Zed.wxs
        run: |
          mkdir -p installer
          cat << 'EOF' > installer/Zed.wxs
          <?xml version="1.0" encoding="UTF-8"?>
          <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
            <Product Id="*" Name="Zed" Language="1033" Version="1.0.0.0" Manufacturer="YourName" UpgradeCode="PUT-YOUR-GUID-HERE">
              <Package InstallerVersion="500" Compressed="yes" InstallScope="perMachine"/>
              <Directory Id="TARGETDIR" Name="SourceDir">
                <Directory Id="ProgramFilesFolder">
                  <Directory Id="INSTALLFOLDER" Name="Zed"/>
                </Directory>
                <Directory Id="ProgramMenuFolder">
                  <Directory Id="ZedStartMenu" Name="Zed"/>
                </Directory>
              </Directory>
              <ComponentGroup Id="ZedExeGroup">
                <Component Id="ZedExeComponent" Guid="PUT-ANOTHER-GUID">
                  <File Id="ZedExe" Source="target/x86_64-pc-windows-gnu/release/zed.exe" KeyPath="yes" />
                </Component>
              </ComponentGroup>
              <Feature Id="ProductFeature" Title="Zed" Level="1">
                <ComponentRef Id="ZedExeComponent"/>
                <Component Id="StartMenuShortcutComponent" Guid="PUT-ANOTHER-GUID">
                  <Shortcut Id="StartMenuShortcut"
                            Name="Zed"
                            Description="Launch Zed"
                            Target="[INSTALLFOLDER]zed.exe"
                            WorkingDirectory="INSTALLFOLDER"/>
                  <RemoveFolder Id="ZedStartMenuFolder" Directory="ZedStartMenu" On="uninstall"/>
                  <RegistryValue Root="HKCU" Key="Software\Zed" Name="installed" Type="integer" Value="1" KeyPath="yes"/>
                </Component>
              </Feature>
            </Product>
          </Wix>
          EOF

      - name: Package MSI with WiX
        working-directory: installer
        run: |
          wine candle.exe -arch x64 Zed.wxs -out Zed.wixobj
          wine light.exe Zed.wixobj -ext WixUIExtension -o ../Zed.msi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            target/x86_64-pc-windows-gnu/release/zed.exe
            Zed.msi
