name: CI (Build zed.msi)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-msi:
    runs-on: self-hosted
    steps:
      # 1. Check out your code
      - uses: actions/checkout@v3

      # 2. Set up Rust and add the Windows GNU target
      - name: Set up Rust
        uses: actions-rust@v1
        with:
          toolchain: stable
      - name: Add Windows target
        run: rustup target add x86_64-pc-windows-gnu

      # 3. Build the Rust binary for Windows
      - name: Build Release (Windows)
        run: cargo build --release --target x86_64-pc-windows-gnu

      # 4. Install .NET (to run the WiX 4 CLI)
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      # 5. Install WiX 4 CLI as a global .NET tool
      - name: Install WiX 4 CLI
        run: dotnet tool install --global wix --version 4.0.5

      # 6. Generate your installer.wxs from the XML snippet
      - name: Generate installer.wxs
        run: |
          cat > installer.wxs << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
            <Product Id="*" Name="Zed" Language="1033" Version="1.0.0.0" Manufacturer="YourName" UpgradeCode="PUT-YOUR-GUID-HERE">
              <Package InstallerVersion="500" Compressed="yes" InstallScope="perMachine"/>
              <Directory Id="TARGETDIR" Name="SourceDir">
                <Directory Id="ProgramFilesFolder">
                  <Directory Id="INSTALLFOLDER" Name="Zed"/>
                </Directory>
                <Directory Id="ProgramMenuFolder">
                  <Directory Id="ZedStartMenu" Name="Zed"/>
                </Directory>
              </Directory>
              <ComponentGroup Id="ZedExeGroup">
                <Component Id="ZedExeComponent" Guid="PUT-ANOTHER-GUID">
                  <File Id="ZedExe" Source="target/x86_64-pc-windows-gnu/release/zed.exe" KeyPath="yes" />
                </Component>
              </ComponentGroup>
              <Feature Id="ProductFeature" Title="Zed" Level="1">
                <ComponentRef Id="ZedExeComponent"/>
                <Component Id="StartMenuShortcutComponent" Guid="PUT-ANOTHER-GUID">
                  <Shortcut Id="StartMenuShortcut"
                            Name="Zed"
                            Description="Launch Zed"
                            Target="[INSTALLFOLDER]zed.exe"
                            WorkingDirectory="INSTALLFOLDER"/>
                  <RemoveFolder Id="ZedStartMenuFolder" Directory="ZedStartMenu" On="uninstall"/>
                  <RegistryValue Root="HKCU" Key="Software\Zed" Name="installed" Type="integer" Value="1" KeyPath="yes"/>
                </Component>
              </Feature>
            </Product>
          </Wix>
          EOF

      # 7. Build the MSI
      - name: Build MSI
        env:
          PATH: ${{ runner.tool_cache }}/dotnet-tools:$PATH
        run: |
          # ensure the dotnet‐tool install dir is on PATH
          export PATH="$HOME/.dotnet/tools:$PATH"
          wix build installer.wxs -o zed.msi

      # 8. Upload the MSI as a workflow artifact
      - name: Upload MSI
        uses: actions/upload-artifact@v3
        with:
          name: zed-installer
          path: zed.msi
