name: CI – Build Windows on Linux

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: self-hosted      # ← picks up your new LXC runner
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build zed for Windows
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --target ${{ matrix.target }}

      - name: Package standalone EXE
        run: |
          mkdir -p out/zed
          cp target/${{ matrix.target }}/release/zed.exe out/zed/

      - name: Create MSI installer via WiX
        run: |
          # generate .wxs including first-install folders:
          cat <<'EOF' > installer/zed.wxs
          <?xml version="1.0" encoding="UTF-8"?>
          <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
            <Product Id="*" Name="zed" Language="1033" Version="1.0.0" Manufacturer="YourName" UpgradeCode="PUT-GUID-HERE">
              <Package InstallerVersion="500" Compressed="yes" InstallScope="perMachine" />
              <Directory Id="TARGETDIR" Name="SourceDir">
                <Directory Id="ProgramFilesFolder">
                  <Directory Id="INSTALLFOLDER" Name="zed" />
                </Directory>
                <Directory Id="ProgramMenuFolder">
                  <Directory Id="ApplicationProgramsFolder" Name="zed" />
                </Directory>
              </Directory>
              <DirectoryRef Id="INSTALLFOLDER">
                <Component Id="zedExe" Guid="PUT-GUID-HERE">
                  <File Id="zed.exe" Source="$(var.SourceDir)\out\zed\zed.exe" KeyPath="yes" />
                </Component>
              </DirectoryRef>
              <Feature Id="DefaultFeature" Level="1">
                <ComponentRef Id="zedExe" />
              </Feature>
            </Product>
          </Wix>
          EOF
          candle -dSourceDir="$(pwd)" installer/zed.wxs
          light -ext WixUIExtension installer/zed.wixobj -o out/zed-installer.msi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zed-windows
          path: |
            out/zed/zed.exe
            out/zed-installer.msi
