name: Compile Zed on Linux for Windows

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-pc-windows-gnu  # cross-compile GNU toolchain
          # - x86_64-pc-windows-msvc  # if you install MSVC toolchain on Linux

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup default stable
          rustup target add ${{ matrix.target }}

      - name: Build for ${{ matrix.target }}
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Install WiX (wine + wix on Linux runner)
        run: |
          sudo apt-get update && sudo apt-get install -y wine-development
          # Download and install WiX Toolset under Wine
          wget -O wix.exe https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe
          wine wix.exe /quiet

      - name: Generate MSI via WiX
        run: |
          cat > installer.wxs << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
            <Product Id="*" Name="zed" Language="1033" Version="1.0.0" Manufacturer="YourName" UpgradeCode="PUT-GUID-HERE">
              <Package InstallerVersion="500" Compressed="yes" InstallScope="perMachine" />
              <Directory Id="TARGETDIR" Name="SourceDir">
                <Directory Id="ProgramFilesFolder">
                  <Directory Id="INSTALLFOLDER" Name="zed" />
                </Directory>
                <Directory Id="ProgramMenuFolder">
                  <Directory Id="ApplicationProgramsFolder" Name="zed" />
                </Directory>
              </Directory>
              <DirectoryRef Id="INSTALLFOLDER">
                <Component Id="zedExe" Guid="PUT-GUID-HERE">
                  <File Source="target/${{ matrix.target }}/release/zed.exe" KeyPath="yes"/>
                </Component>
              </DirectoryRef>
              <DirectoryRef Id="ApplicationProgramsFolder">
                <Component Id="StartMenuShortcut" Guid="PUT-GUID-HERE">
                  <Shortcut Id="zedShortcut"
                            Name="zed"
                            Description="Launch zed"
                            Target="[INSTALLFOLDER]zed.exe"
                            WorkingDirectory="INSTALLFOLDER" />
                  <RemoveFolder Id="RemoveProgramMenuDir" On="uninstall"/>
                  <RegistryValue Root="HKCU" Key="Software\zed" Name="installed" Type="integer" Value="1" KeyPath="yes"/>
                </Component>
              </DirectoryRef>
              <Feature Id="DefaultFeature" Level="1">
                <ComponentRef Id="zedExe" />
                <ComponentRef Id="StartMenuShortcut" />
              </Feature>
            </Product>
          </Wix>
          EOF
          wine candle installer.wxs
          wine light -ext WixUIExtension installer.wixobj -o zed-installer.msi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zed-windows-${{ matrix.target }}
          path:
            - target/${{ matrix.target }}/release/zed.exe
            - zed-installer.msi
