name: Build Zed Windows Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust, target & mingw
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          rustup default stable
          rustup target add x86_64-pc-windows-gnu
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Build zed.exe
        run: |
          source $HOME/.cargo/env
          cargo build --release --target x86_64-pc-windows-gnu

      - name: Install .NET 7 SDK
        run: |
          wget https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb \
            -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-7.0

      - name: Install WiX CLI
        run: |
          dotnet tool install --global wix
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Create installer.wxs
        run: |
          cat << 'EOF' > installer.wxs
          <?xml version="1.0" encoding="UTF-8"?>
          <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
            <Product Id="*" Name="Zed" Language="1033" Version="1.0.0.0" Manufacturer="YourName" UpgradeCode="PUT-YOUR-GUID-HERE">
              <Package InstallerVersion="500" Compressed="yes" InstallScope="perMachine"/>
              <Directory Id="TARGETDIR" Name="SourceDir">
                <Directory Id="ProgramFilesFolder">
                  <Directory Id="INSTALLFOLDER" Name="Zed"/>
                </Directory>
                <Directory Id="ProgramMenuFolder">
                  <Directory Id="ZedStartMenu" Name="Zed"/>
                </Directory>
              </Directory>
              <ComponentGroup Id="ZedExeGroup">
                <Component Id="ZedExeComponent" Guid="PUT-ANOTHER-GUID">
                  <File Id="ZedExe" Source="target/x86_64-pc-windows-gnu/release/zed.exe" KeyPath="yes" />
                </Component>
              </ComponentGroup>
              <Feature Id="ProductFeature" Title="Zed" Level="1">
                <ComponentRef Id="ZedExeComponent"/>
                <Component Id="StartMenuShortcutComponent" Guid="PUT-ANOTHER-GUID">
                  <Shortcut
                    Id="StartMenuShortcut"
                    Name="Zed"
                    Description="Launch Zed"
                    Target="[INSTALLFOLDER]zed.exe"
                    WorkingDirectory="INSTALLFOLDER"/>
                  <RemoveFolder Id="ZedStartMenuFolder" Directory="ZedStartMenu" On="uninstall"/>
                  <RegistryValue
                    Root="HKCU"
                    Key="Software\Zed"
                    Name="installed"
                    Type="integer"
                    Value="1"
                    KeyPath="yes"/>
                </Component>
              </Feature>
            </Product>
          </Wix>
          EOF

      - name: Build MSI
        run: |
          wix build installer.wxs -o zed.msi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zed-windows-installer
          path: |
            target/x86_64-pc-windows-gnu/release/zed.exe
            zed.msi
