name: Build Windows MSI & EXE

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    # Läuft nur auf deinem selbstgehosteten Linux-Runner
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          rustup default stable
          rustup target add x86_64-pc-windows-gnu

      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 cmake wine unzip zip

      - name: Build Windows release
        env:
          RUSTFLAGS: -C codegen-units=1
        run: |
          cargo build --release --target x86_64-pc-windows-gnu --jobs 1

      - name: Copy EXE to workspace root
        run: |
          cp target/x86_64-pc-windows-gnu/release/zed.exe ./zed.exe

      - name: Download & extract WiX Toolset 3.11.2
        run: |
          curl -L --fail -o wix.zip \
            https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
          unzip wix.zip -d wix
          echo "${PWD}/wix/bin" >> $GITHUB_PATH

      - name: Package MSI with WiX
        run: |
          candle.exe -arch x64 -out installer.wixobj installer.wxs
          light.exe -out zed.msi installer.wixobj

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zed-windows
          path:
            - zed.exe
            - zed.msi
