name: build-windows for windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      # Cache crates.io index and downloads
      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      # Cache compiled artifacts
      - name: Cache Cargo build artifacts
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-

      # Speed up Rust rebuilds
      - name: Install sccache
        run: cargo install sccache
        shell: pwsh
      - name: Configure sccache
        run: |
          echo "RUSTC_WRAPPER=$(where sccache.exe)" >> $GITHUB_ENV
          echo "SCCACHE_CACHE_SIZE=10G"      >> $GITHUB_ENV
        shell: pwsh

      # Install DirectX End-User Runtimes metapackage
      - name: Install DirectX
        run: choco install directx -y
        shell: pwsh

      # Set up CMake & Rust
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: 3.26.4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Build & run
      - name: Build release
        run: cargo build --release

      - name: Run Zed (with backtraces)
        run: target\release\zed.exe
        env:
          RUST_BACKTRACE: 1
